#cloud-config
repo_update: true

packages:
- apache2

runcmd:
- systemctl start apache2
- systemctl enable apache2

users:
- default
- name: ${ec2_user}
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  ssh_authorized_keys:
  - ${ssh_key}